"""
Adds 'Images were generated by AI' disclaimer to top-right of hero image.
Run once after replacing images/hero.png. Output overwrites hero.png.
"""
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "images" / "hero.png"
OUT = ROOT / "images" / "hero.png"

img = Image.open(SRC).convert("RGBA")
W, H = img.size

# Pick a font size proportional to image width (~1.4% of width)
font_size = max(14, int(W * 0.014))
font = None
for candidate in [
    "C:/Windows/Fonts/arialbd.ttf",
    "C:/Windows/Fonts/arial.ttf",
    "C:/Windows/Fonts/segoeuib.ttf",
]:
    try:
        font = ImageFont.truetype(candidate, font_size)
        break
    except OSError:
        continue
if font is None:
    font = ImageFont.load_default()

text = "Images were generated by AI"

# Measure text
draw = ImageDraw.Draw(img)
bbox = draw.textbbox((0, 0), text, font=font)
text_w = bbox[2] - bbox[0]
text_h = bbox[3] - bbox[1]

# Padding & position (top-right corner)
pad_x = int(font_size * 0.7)
pad_y = int(font_size * 0.45)
margin = int(W * 0.012)

box_w = text_w + pad_x * 2
box_h = text_h + pad_y * 2
box_x = W - margin - box_w
box_y = margin

# Semi-transparent dark pill behind text for legibility
overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
od = ImageDraw.Draw(overlay)
od.rounded_rectangle(
    [box_x, box_y, box_x + box_w, box_y + box_h],
    radius=int(font_size * 0.5),
    fill=(0, 0, 0, 165),
)

# Compose overlay
img = Image.alpha_composite(img, overlay)

# Draw text on top
draw = ImageDraw.Draw(img)
text_x = box_x + pad_x - bbox[0]
text_y = box_y + pad_y - bbox[1]
draw.text((text_x, text_y), text, fill=(255, 255, 255, 255), font=font)

# Save back as PNG
img.convert("RGB").save(OUT, "PNG", optimize=True)
print(f"OK -> {OUT} ({W}x{H}, font={font_size}px)")
